- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineRailgunPeregrine
  result: MagazineRailgunPeregrineEmpty
  completetime: 10
  materials:
    Plasteel: 500
    Plastic: 500
    Steel: 500
    Glass: 200
    Silver: 50
    Gold: 50

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxRailgunPeregrine
  result: MagazineRailgunPeregrineEmpty
  completetime: 10
  materials:
    Plasteel: 500
    Plastic: 500
    Steel: 500
    Glass: 200
    Silver: 50
    Gold: 50

# Security Borg limbs

- type: latheRecipe
  parent: BaseBorgLimbRecipe
  id: LeftLegBorgSecurity
  result: LeftLegBorgSecurity

- type: latheRecipe
  parent: BaseBorgLimbRecipe
  id: RightLegBorgSecurity
  result: RightLegBorgSecurity

- type: latheRecipe
  parent: BaseBorgLimbRecipe
  id: HeadBorgSecurity
  result: HeadBorgSecurity

- type: latheRecipe
  parent: BaseBorgLimbRecipe
  id: TorsoBorgSecurity
  result: TorsoBorgSecurity
